version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: one-to-rule-them-all
    volumes:
      - ./volumes/db/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis
    ports:
      - '6379:6379'
  api:
    build:
      context: ./api
    depends_on:
      - redis
      - postgres
    ports:
      - '4000:4000'
