version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: one-to-rule-them-all
    volumes:
      - ./volumes/db/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis
  api:
    image: tylerauer/one-api:latest
    depends_on:
      - redis
      - db
    ports:
      - '4000:4000'
